INSERT INTO PUBLIC.OLDSKOOL(ID, DATA) VALUES (11, 'my first data');
INSERT INTO PUBLIC.OLDSKOOL(ID, DATA) VALUES (22, 'my second data');
INSERT INTO PUBLIC.OLDSKOOL(ID, DATA) VALUES (33, 'my third data');

