INSERT INTO PUBLIC.SIMPLE(ID, DATA) VALUES (11, 'my first data');
INSERT INTO PUBLIC.SIMPLE(ID, DATA) VALUES (22, 'my second data');
INSERT INTO PUBLIC.SIMPLE(ID, DATA) VALUES (33, 'my third data');


INSERT INTO PUBLIC.ANNOTATED(ID, DATA) VALUES (12, 'my first data');

