INSERT INTO PUBLIC.INHERIT(ID, DATA) VALUES (11, 'my first data');
INSERT INTO PUBLIC.INHERIT(ID, DATA) VALUES (22, 'my second data');
INSERT INTO PUBLIC.INHERIT(ID, DATA) VALUES (33, 'my third data');
INSERT INTO PUBLIC.INHERIT2(ID, DATA) VALUES (11, 'my first data');
INSERT INTO PUBLIC.INHERIT2(ID, DATA) VALUES (22, 'my second data');
INSERT INTO PUBLIC.INHERIT2(ID, DATA) VALUES (33, 'my third data');

