INSERT INTO PUBLIC.PRODUCTS(ID, NAME, VERSION) VALUES  (1, 'Butifarra',0);
INSERT INTO PUBLIC.PRODUCTS(ID, NAME, VERSION) VALUES (2, 'Bull',0);
INSERT INTO PUBLIC.PRODUCTS(ID, NAME, VERSION) VALUES  (3, 'Fuet',0);
INSERT INTO PUBLIC.ORDERS(ID, ORDERNUMBER, VERSION) VALUES (1, 'AAAAAAA1',0);
INSERT INTO PUBLIC.ORDERS(ID, ORDERNUMBER, VERSION) VALUES (2, 'AAAAAAA2',0);
INSERT INTO PUBLIC.ORDERS(ID, ORDERNUMBER, VERSION) VALUES (3, 'AAAAAAA3',0);
INSERT INTO PUBLIC.ORDERS(ID, ORDERNUMBER, VERSION) VALUES (4, 'AAAAAAA4',0);
INSERT INTO PUBLIC.ORDER_ITEMS(ID, PRODUCT_ID, ORDER_ID,QUANTITY,VERSION) VALUES(1,1,1,2,0),(2,1,2,12,0),(3,1,3,24,0),(4,2,1,3,0),(5,2,2,33,0),(6,2,3,25,0),(7,3,1,3,0),(8,3,2,33,0),(9,3,3,25,0);
INSERT INTO PUBLIC.ORDER_ITEMS(ID, PRODUCT_ID, ORDER_ID,QUANTITY,VERSION) VALUES(10,1,4,10,0);
