INSERT INTO PUBLIC.USERS(ID, USERNAME) VALUES (1,'JUAN');
INSERT INTO PUBLIC.USERS(ID, USERNAME) VALUES (2,'PEDRO');
INSERT INTO PUBLIC.USERS(ID, USERNAME) VALUES (3,'LUIS');
INSERT INTO PUBLIC.USER_EXTS(USER_ID,FACEBOOK_ACCOUNT,TWITTER_ACCOUNT) VALUES(1, 'juan@facebook', 'juan@witter');
INSERT INTO PUBLIC.USER_EXTS(USER_ID,FACEBOOK_ACCOUNT,TWITTER_ACCOUNT) VALUES(2, 'pedro@facebook', 'pedro@witter');
INSERT INTO PUBLIC.USER_EXTS(USER_ID,FACEBOOK_ACCOUNT,TWITTER_ACCOUNT) VALUES(3, 'luis@facebook', 'luis@witter');



