INSERT INTO PUBLIC.country (id,name) VALUES('UG','UGANDA');
INSERT INTO PUBLIC.country (id,name) VALUES('UA','UKRAINE');
INSERT INTO PUBLIC.country (id,name) VALUES('AE','UNITED ARAB EMIRATES');
INSERT INTO PUBLIC.country (id,name) VALUES('GB','UNITED KINGDOM');
INSERT INTO PUBLIC.country (id,name) VALUES('US','UNITED STATES');
INSERT INTO PUBLIC.country (id,name) VALUES('UM','UNITED STATES MINOR OUTLYING ISLANDS');
INSERT INTO PUBLIC.country (id,name) VALUES('UY','URUGUAY');
INSERT INTO PUBLIC.country (id,name) VALUES('UZ','UZBEKISTAN');
INSERT INTO PUBLIC.country (id,name) VALUES('VU','VANUATU');
INSERT INTO PUBLIC.country (id,name) VALUES('VA','VATICAN CITY STATE (HOLY SEE)');
INSERT INTO PUBLIC.country (id,name) VALUES('VE','VENEZUELA');
INSERT INTO PUBLIC.country (id,name) VALUES('VN','VIET NAM');
INSERT INTO PUBLIC.country (id,name) VALUES('VG','VIRGIN ISLANDS (BRITISH)');
INSERT INTO PUBLIC.country (id,name) VALUES('VI','VIRGIN ISLANDS (U.S.)');
INSERT INTO PUBLIC.country (id,name) VALUES('WF','WALLIS AND FUTUNA ISLANDS');
INSERT INTO PUBLIC.country (id,name) VALUES('EH','WESTERN SAHARA');
INSERT INTO PUBLIC.country (id,name) VALUES('YE','YEMEN');
INSERT INTO PUBLIC.country (id,name) VALUES('ZM','ZAMBIA');
INSERT INTO PUBLIC.country (id,name) VALUES('ZW','ZIMBABWE');


INSERT INTO PUBLIC.company (id,name, country_id) VALUES('B1','HOUSEWARE','YE');
INSERT INTO PUBLIC.company (id,name, country_id) VALUES('B2','SETTING','YE');