INSERT INTO PUBLIC.PRODUCTS(ID, NAME) VALUES ('AAA1', 'Butifarra'), ('AAA2', 'Bull'), ('AAA3', 'Fuet');
INSERT INTO PUBLIC.COUNTRIES(ID, NAME) VALUES('ES', 'España'), ('CA', 'Catalunya'), ('FR', 'Francia');
INSERT INTO PUBLIC.PRICES(PRODUCT_ID, COUNTRY_ID,VALUE) VALUES('AAA1','ES', 1.1),('AAA2','ES', 0.81),('AAA3','ES', 0.24);
INSERT INTO PUBLIC.PRICES(PRODUCT_ID, COUNTRY_ID,VALUE) VALUES('AAA1','CA', 1.21),('AAA2','CA', 0.91),('AAA3','CA', 0.34);
INSERT INTO PUBLIC.PRICES(PRODUCT_ID, COUNTRY_ID,VALUE) VALUES('AAA1','FR', 1.0),('AAA2','FR', 0.70),('AAA3','FR', 0.2);
