INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('UG','UGANDA',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('UA','UKRAINE',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('AE','UNITED ARAB EMIRATES',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('GB','UNITED KINGDOM',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('US','UNITED STATES',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('UM','UNITED STATES MINOR OUTLYING ISLANDS',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('UY','URUGUAY',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('UZ','UZBEKISTAN',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('VU','VANUATU',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('VA','VATICAN CITY STATE (HOLY SEE)',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('VE','VENEZUELA',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('VN','VIET NAM',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('VG','VIRGIN ISLANDS (BRITISH)',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('VI','VIRGIN ISLANDS (U.S.)',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('WF','WALLIS AND FUTUNA ISLANDS',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('EH','WESTERN SAHARA',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('YE','YEMEN',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('ZM','ZAMBIA',1,0);
INSERT INTO PUBLIC.Country (Id,Name, Enabled, Version) VALUES('ZW','ZIMBABWE',1,0);